src/Entity/Commune.php
<?php

namespace App\Entity;

use App\Repository\CommuneRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommuneRepository::class)]
class Commune
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $code_insee = null;

    #[ORM\Column(length: 255)]
    private ?string $name_commune = null;

    #[ORM\Column(length: 255)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeInsee(): ?string
    {
        return $this->code_insee;
    }

    public function setCodeInsee(string $code_insee): static
    {
        $this->code_insee = $code_insee;

        return $this;
    }

    public function getNameCommune(): ?string
    {
        return $this->name_commune;
    }

    public function setNameCommune(string $name_commune): static
    {
        $this->name_commune = $name_commune;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }
}

src/Form/CommuneType.php
<?php

namespace App\Form;

use App\Entity\Commune;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommuneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('code_insee')
            ->add('name_commune')
            ->add('code_postal')
            ->add('libelle')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commune::class,
        ]);
    }
}

src/Controller/CommuneController.php
<?php

namespace App\Controller;

use App\Entity\Commune;
use App\Form\CommuneType;
use App\Repository\CommuneRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/commune')]
class CommuneController extends AbstractController
{
    #[Route('/', name: 'app_commune_index', methods: ['GET'])]
    public function index(CommuneRepository $communeRepository): Response
    {
        return $this->render('commune/index.html.twig', [
            'communes' => $communeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_commune_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commune = new Commune();
        $form = $this->createForm(CommuneType::class, $commune);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($commune);
            $entityManager->flush();

            return $this->redirectToRoute('app_commune_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commune/new.html.twig', [
            'commune' => $commune,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commune_show', methods: ['GET'])]
    public function show(Commune $commune): Response
    {
        return $this->render('commune/show.html.twig', [
            'commune' => $commune,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_commune_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commune $commune, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommuneType::class, $commune);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_commune_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commune/edit.html.twig', [
            'commune' => $commune,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_commune_delete', methods: ['POST'])]
    public function delete(Request $request, Commune $commune, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commune->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commune);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commune_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\User;
use App\Entity\Commune;
use Doctrine\ORM\EntityManagerInterface;

use App\Services\Avatar;


class UserController extends AbstractController
{
    #[Route('/', name: 'app_user')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $users = $entityManager->getRepository(User::class)->findAll();

        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
            'users' => $users,
        ]);
    }

    #[Route('/new_avatar', name: 'new_avatar_user')]
    public function new_avatar(EntityManagerInterface $entityManager): Response
    {
        $avatar = new Avatar();
        // change size
        $IMG_Avatar = $avatar->getAvatar();

        return $this->render('services/index.html.twig', [
            'avatar'=>$IMG_Avatar,
        ]);
    }

    #[Route('/communes', name: 'communes')]
    public function list_commune(EntityManagerInterface $entityManager): Response
    {
        $communes = $entityManager->getRepository(Commune::class)->findAll();

        return $this->render('communes/list_commune.html.twig', [
            'controller_name' => 'UserController',
            'communes' => $communes,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
        <style>
            body{
               font-family: 'Montserra', sans-serif;
            }
            .avatar{
                width: 100px;
                height: 100px;
            }
        </style>
    </head>
    <body>
    <main>
        {% block body %}
            Hello World!
        {% endblock %}
    </main>
    </body>
</html>

templates/commune/_delete_form.html.twig
<form method="post" action="{{ path('app_commune_delete', {'id': commune.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commune.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commune/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commune/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commune{% endblock %}

{% block body %}
    <h1>Edit Commune</h1>

    {{ include('commune/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_commune_index') }}">back to list</a>

    {{ include('commune/_delete_form.html.twig') }}
{% endblock %}

templates/commune/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commune index{% endblock %}

{% block body %}
    <h1>Commune index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code_insee</th>
                <th>Name_commune</th>
                <th>Code_postal</th>
                <th>Libelle</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commune in communes %}
            <tr>
                <td>{{ commune.id }}</td>
                <td>{{ commune.codeInsee }}</td>
                <td>{{ commune.nameCommune }}</td>
                <td>{{ commune.codePostal }}</td>
                <td>{{ commune.libelle }}</td>
                <td>
                    <a href="{{ path('app_commune_show', {'id': commune.id}) }}">show</a>
                    <a href="{{ path('app_commune_edit', {'id': commune.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commune_new') }}">Create new</a>
{% endblock %}

templates/commune/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commune{% endblock %}

{% block body %}
    <h1>Create new Commune</h1>

    {{ include('commune/_form.html.twig') }}

    <a href="{{ path('app_commune_index') }}">back to list</a>
{% endblock %}

templates/commune/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commune{% endblock %}

{% block body %}
    <h1>Commune</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commune.id }}</td>
            </tr>
            <tr>
                <th>Code_insee</th>
                <td>{{ commune.codeInsee }}</td>
            </tr>
            <tr>
                <th>Name_commune</th>
                <td>{{ commune.nameCommune }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ commune.codePostal }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ commune.libelle }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commune_index') }}">back to list</a>

    <a href="{{ path('app_commune_edit', {'id': commune.id}) }}">edit</a>

    {{ include('commune/_delete_form.html.twig') }}
{% endblock %}

templates/services/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}

<div>
    {# On liste tout les user #}
    <h1>Avatar</h1>
    {{ avatar | raw }}
</div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}

<div>
    {# On liste tout les user #}
    <h1>Liste des utilisateurs</h1>
    <ul>
        {% for user in users %}
            <li>{{ user.name }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}